id: 564efacaddfb40278c37f6422f4090a3
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_207-Strength_of_the_Elephant-v2
  language: en
  author: ''
  volume: {}
